### ISSUE TITLE
cocostuff

### ISSUE THREAD

**Issue by RainHxj** [MendelXu/zsseg.baseline#1]
unzipping the stuff_annotations_trainval2017.zip, I cannot obtain "stuffthingmaps" folder.

**Comment by MendelXu** [comment]
I am sorry to assign wrong link. The true link is http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip. I will update the readme.

**Comment by RainHxj** [comment]
Thanks for your answer. In Table 5 of this paper, you evaluate the generalization ability of the mask proposal generator. Where can I find the code of evaluation?

**Comment by MendelXu** [comment]
For example, evaluate the quality of proposals on ade20k
```
python train_net.py --config-file configs/coco-stuff-164k-171/maskformer_R101c_bs32_60k.yaml --eval-only --num-gpus 8 ORACLE True MODEL.META_ARCHITECTURE OracleMaskFormer MODEL.WEIGHTS ${TRAINED_MODEL}
```
Here `${TRAINED_MODEL}` is a checkpoint trained on ADE20k.

**Comment by MendelXu** [comment]
Concretely, it will run this model. https://github.com/MendelXu/zsseg.baseline/blob/master/mask_former/ablation/oracle_mask_former_model.py

**Comment by RainHxj** [comment]
Thanks. The "region_clip_adapter" is used to provide a prediction for model ensembling. How to train a region_clip_adapter and how to load the trained checkpoint?

**Comment by MendelXu** [comment]
It has been mentioned in the readme.
```
# Training prompts
python train_net.py --config-file configs/coco-stuff-164k-156/zero_shot_proposal_classification_learn_prompt_bs32_10k.yaml --num-gpus 8 
# Training seg model
python train_net.py --config-file configs/coco-stuff-164k-156/zero_shot_maskformer_R101c_bs32_60k.yaml --num-gpus 8 MODEL.CLIP_ADAPTER.PROMPT_CHECKPOINT ${TRAINED_PROMPTS}
```
