### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by NickChang97** [MendelXu/zsseg.baseline#10]
For evaluation, add --eval-only flag to the traing command.  Only --eval-only seems not right. I only get the result of model which is initialized from ImageNet pre-train.

**Comment by NickChang97** [comment]
Add extra --resume, it evaluate the model_final.pth

**Comment by AnukritiSinghh** [comment]
Can you share the whole command please?

**Comment by NickChang97** [comment]
"python train_net.py --config-file configs/coco-stuff-164k-156/zero_shot_maskformer_R101c_single_prompt_bs32_60k.yaml --eval-only --resume" can start evaluation of the model_final.pth,  without --resume, only ImageNet pre-train is loaded to evaluate.
