### ISSUE TITLE
Questions about VOC dataset directorys

### ISSUE THREAD

**Issue by zichengsaber** [MendelXu/zsseg.baseline#11]
For VOC dataset dir，I download the dataset from the link you provide but it still confused me a lot，can you explain more clear in README？

**Comment by MendelXu** [comment]
You can use https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_json_results.py to visualize the segmentation result.

**Comment by zichengsaber** [comment]
Thanks for your answering，pardon my stupidity，I still have some questions:
```bash
  datasets/
     VOC2012/
          #http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar
          JPEGImages/
          val.txt
          #http://home.bharathh.info/pubs/codes/SBD/download.html
          SegmentationClassAug/
          #https://gist.githubusercontent.com/sun11/2dbda6b31acc7c6292d14a872d0c90b7/raw/5f5a5270089239ef2f6b65b1cc55208355b5acca/trainaug.txt
          train.txt
          
  ```


1. Is the `val.txt` the same as VOC2012 `ImageSets/Segmentation/val.txt`
2. the `*.png` in `SegmentationClassAug/` from where? I download the SBD but it like that
```bash
benchmark_RELEASE/
       dataset/
             cls/
             img/
             train.txt
             val.txt


```
The images in `img/` are `*.jpg`
3. is the `train.txt` the same as `trainaug.txt`?

**Comment by MendelXu** [comment]
1. Yes.
2. You have t convert the  Matlab file in `cls/` to png file in `SegmentationClass Aug`. As I get the data from others, I have omitted this step. You may use https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/data/pascal/convert_sbdd.py to convert it.
3. Yes.

**Comment by AnukritiSinghh** [comment]
hey @zichengsaber, how did you download the SBD? what did you use?

**Comment by zichengsaber** [comment]
The directory SegmentationClassAug from here

https://www.dropbox.com/s/oeu149j8qtbs1x0/SegmentationClassAug.zip?dl=0

Anukriti Singh ***@***.***> 于2022年7月27日周三 23:03写道：

**Comment by AnukritiSinghh** [comment]
Thank you so much, I was able to figure it out. However, can you share what command you used to convert for running convert_sbdd.py?

**Comment by zichengsaber** [comment]
I didn't use the convert scripts, just download SegmentationClassAug from
the link, which has already made the convert I guess, I learnt the
relationship between VOC2012 and SBD from this Chinese blog:
`https://blog.csdn.net/lscelory/article/details/98180917` , And also this
link maybe helpful `
https://github.com/BebDong/MXNetSeg/tree/main/scripts/PascalVOCAug`

Anukriti Singh ***@***.***> 于2022年7月28日周四 21:11写道：
