### ISSUE TITLE
Visualization of PASCAL VOC predicted masks

### ISSUE THREAD

**Issue by prinshul** [MendelXu/zsseg.baseline#12]
Hi,

Thanks for sharing your code.

After training and testing with PASCAL VOC, I am getting very bad masks that do not correspond to the IoU score during the evaluation. For example class "train" IoU is 92 but predicted masks are very poor.

Can you please provide the visualization script?

Thank you.

**Comment by MendelXu** [comment]
You can use https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_json_results.py to visualize the segmentation result.

**Comment by prinshul** [comment]
> You can use https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_json_results.py to visualize the segmentation result.

The detectron2 visualisation requires image_id in the predictions, but the predictions here only have file_name. https://github.com/facebookresearch/detectron2/blob/48b598b4f61fbb24182a69b521b2a0ba3252b842/tools/visualize_json_results.py#L58

Can you please share the script you used for the same format in which predictions are stored?

**Comment by MendelXu** [comment]
I have written a script to visualize the result with wandb, but I didn't test it on Pascal VOC. I will share it here later after testing.

**Comment by AnukritiSinghh** [comment]
can you share the script used for coco then? @MendelXu

**Comment by MendelXu** [comment]
> can you share the script used for coco then? @MendelXu

See https://gist.github.com/MendelXu/052d65bd51c48887274fd985eb0f3ad1

**Comment by prinshul** [comment]
> > can you share the script used for coco then? @MendelXu
> 
> See https://gist.github.com/MendelXu/052d65bd51c48887274fd985eb0f3ad1. Use it like
> 
> ```
> python tools/visualization.py method1=outputs/method1_predictions.json,method2=outputs/method2_sem_seg_predictions.json --dataset_name=coco_2017_test_stuff_sem_seg --wandb_title="debug" --novel-only
> ```

Thank you for providing the script.

**Comment by NanAlbert** [comment]
> > can you share the script used for coco then? @MendelXu
> 
> See https://gist.github.com/MendelXu/052d65bd51c48887274fd985eb0f3ad1. Use it like
> 
> ```
> python tools/visualization.py method1=outputs/method1_predictions.json,method2=outputs/method2_sem_seg_predictions.json --dataset_name=coco_2017_test_stuff_sem_seg --wandb_title="debug" --novel-only
> ```

Hi, 
I want to thank you for your excellent work. However, I am still uncertain about the purpose of "outputs/method1_predictions.json" and "outputs/method2_sem_seg_predictions.json". Currently, I only have access to the "./output/inference/sem_seg_predictions.json" file. Could you please provide further instructions on how to obtain the necessary files for visualization? 
Thank you!

**Comment by NanAlbert** [comment]
> 

Hi,
Were you able to successfully generate the visualization? I'm still unsure how to obtain "outputs/method1_predictions.json" and "outputs/method2_sem_seg_predictions.json". Could you please provide some assistance? Thank you very much. 


Did you successfully complete the visualization? I still don't know how to get file 1 and file 2. Can you help, thank you enough.

**Comment by NanAlbert** [comment]
> > > can you share the script used for coco then? @MendelXu
> > 
> > 
> > See https://gist.github.com/MendelXu/052d65bd51c48887274fd985eb0f3ad1. Use it like
> > ```
> > python tools/visualization.py method1=outputs/method1_predictions.json,method2=outputs/method2_sem_seg_predictions.json --dataset_name=coco_2017_test_stuff_sem_seg --wandb_title="debug" --novel-only
> > ```
> 
> Thank you for providing the script.

Hi,
Were you able to successfully generate the visualization? I'm still unsure how to obtain "outputs/method1_predictions.json" and "outputs/method2_sem_seg_predictions.json". Could you please provide some assistance? Thank you very much.
