### ISSUE TITLE
self-training techniques

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [MendelXu/zsseg.baseline#18]
Thanks for the great work.

I wonder if the self-training techniques (Sec 6.3 in your paper) are implemented in the codes/commands in [https://github.com/MendelXu/zsseg.baseline#training-and-evaluation](https://github.com/MendelXu/zsseg.baseline#training-and-evaluation) by default?

**Comment by MendelXu** [comment]
Answered in the email. The self training code is provided in https://github.com/MendelXu/zsseg.baseline/blob/master/mask_former/evaluation/pseudo_sem_seg_evaluation.py.

**Comment by jiaosiyu-vv** [comment]
Thanks for the great work.
Can you provide a brief introduction to how to use the self-training? 
 I load the pre-trained weights, and get COCO results: `seen IoU 40.3859`, `unseen IoU 36.4862`
When I set `cfg.PSEUDO = Ture,`  get results: `seen IoU 100.0`, `unseen IoU 67.64`
Do you know what went wrong?

**Comment by vamsikrishna7909** [comment]
Can I also get the instruction for self training and evaluation ?
