### ISSUE TITLE
Incorrect detectron2 version in README

### ISSUE THREAD

**Issue by TB5zhh** [MendelXu/zsseg.baseline#2]
[This line](https://github.com/MendelXu/zsseg.baseline/blob/f827a093e41af2d9c069a9a565880c92da1c133e/mask_former/data/build.py#L27) tries to import `RandomSubsetTrainingSampler` from `detectron2`, but this sampler is only available in detectron2 v0.6 (see [here](https://github.com/facebookresearch/detectron2/commit/f410d5b26cbf24998be250649dc73fdc57eb307e)), whereas in README instructions the version of detectron2 is 0.5

**Comment by MendelXu** [comment]
OK~I will fix it.
