### ISSUE TITLE
The result on VOC can not be reached

### ISSUE THREAD

**Issue by AutomanHan** [MendelXu/zsseg.baseline#20]
I run the code on VOC dataset with the config file voc-11k-15/zero_shot_maskformer_R101c_bs16_20k.yaml(https://github.com/MendelXu/zsseg.baseline/blob/master/configs/voc-11k-15/zero_shot_maskformer_R101c_bs16_20k.yaml), the result can not be reached 72.5 miou-unseen. The prompt model weights are trained with config file [voc-11k-15](https://github.com/MendelXu/zsseg.baseline/tree/master/configs/voc-11k-15)/zero_shot_proposal_classification_learn_prompt_bs16_10k.yaml. The best result is 62.85 miou-unseen. Do I miss some configs or do wrong steps? And I change the prompt from "predefined" to "learnable". 
Or you can send the learnable prompt model weights to me. I think the prompt model weights is important in the method.

**Comment by NanAlbert** [comment]
> 
Hello, have you solved the problem? I can't reproduce the results either.

**Comment by lchen1019** [comment]
> > 
> 
> Hello, have you solved the problem? I can't reproduce the results either.

Me too, I get 12.7554 in PC-459, using the pre-trained checkpoint. Have you solved it?
