### ISSUE TITLE
AssertionError: Non-existent key:  MODEL.WEIGHTST

### ISSUE THREAD

**Issue by ylong4** [MendelXu/zsseg.baseline#22]

**Comment by AutomanHan** [comment]
> Hello, I downloaded pre-training weights and follow the Command line, but I got "AssertionError: Non-existent key: MODEL.WEIGHTST", please help me. ![image](https://user-images.githubusercontent.com/95207674/224070825-53f953e3-f4cb-46a9-aed8-19b5a2087134.png) ![image](https://user-images.githubusercontent.com/95207674/224070851-f62dfc22-8ed7-4a33-9f41-1d899146f5b6.png)
It may be `MODEL.WEIGHTS`
