### ISSUE TITLE
Training of ZSL setting and Cross-dataset setting

### ISSUE THREAD

**Issue by NanAlbert** [MendelXu/zsseg.baseline#24]
Thank you for your significant contributions to this field. I have a question regarding your work, particularly concerning the training phases in the zero-shot learning (ZSL) and cross-dataset settings. Though it appears that both settings utilize the same training dataset (156 classes of COCO), I noticed that different best models are provided for different settings. Could you kindly elaborate on the differences between the training phases of the two settings?

**Comment by MendelXu** [comment]
For zero-shot setting, the model is with prompt tuning and shorter schedule.
For cross-dataset setting, the model is with hand-crafted prompts, and longer schedule.

**Comment by NanAlbert** [comment]
> For zero-shot setting, the model is with prompt tuning and shorter schedule. For cross-dataset setting, the model is with hand-crafted prompts, and longer schedule.

Thank you so much. Another question: Why not use prompt learning for the cross-dataset setting? This technique should be able to unlock the power of the CLIP model. 

Thank you again for your contributions and response.

**Comment by MendelXu** [comment]
Yes , you are right. Actually, some latter works have confirmed that. But I failed to make it work well at that time.

**Comment by NanAlbert** [comment]
Thanks!
